### ISSUE TITLE
Start videos in fullscreen not working in 0.8.1

### ISSUE THREAD

**Issue by yihaolee85** [fredrikburmester/streamyfin#105]
**Describe the bug**
I couldn't reopen #71, but starting videos in fullscreen is still not working in the 0.8.1 release.

**To Reproduce**
1. Enable "start videos in fullscreen settings
2. Go to a video and press play 
3. Mini player opens with a spinner while still loading video.
4. Video plays in mini player

**Screenshots**
![IMG_1208](https://github.com/user-attachments/assets/2248b183-d6c3-4dd3-9cd2-6c4de873d8d9)
![IMG_1209](https://github.com/user-attachments/assets/cd6bbfda-e5b2-4c42-af35-fbfd05aca204)
![IMG_1210](https://github.com/user-attachments/assets/6c9683df-4aef-49a7-9aff-849c7a8047ef)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 17.6.1
 - Version 0.8.1

**Comment by fredrikburmester** [comment]
Thank you, it seems this issue is haunting me haha.. Hopefully fixed in 0.8.4.

**Comment by yihaolee85** [comment]
I just tested it on 0.8.4 (5)... unfortunately still the same.
