### ISSUE TITLE
Movie not rotating on Samsung s23+

### ISSUE THREAD

**Issue by seelenverwandter1** [fredrikburmester/streamyfin#27]
**Describe the bug**
When i start a movie rotating the screen has no effect. 

**To Reproduce**
Open the App > Start a movie > rotate the screen to landscale and See that nothing happens. 

**Screenshots**
The Phone is in landscape Mode and all other Apps are rotating without problems. 
![Screenshot_20240813_104103_Streamyfin](https://github.com/user-attachments/assets/0542a7e1-db4a-4f2c-9aff-b66def01b311)

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy s23+]
 - OS: [Android 14 ]
 - Version [0.2.1]

**Comment by fredrikburmester** [comment]
This is fixed in v0.3.1. Please see the releases section.

**Comment by seelenverwandter1** [comment]
I'm now on 0.3.1 and its still the Same.
Neither the playlist nor the video playback rotates.

**Comment by seelenverwandter1** [comment]
https://github.com/user-attachments/assets/65e4dbf8-6f1f-4fea-bff2-540dde5ee818

**Comment by fredrikburmester** [comment]
Please check the new release 0.3.3! @seelenverwandter1

**Comment by seelenverwandter1** [comment]
Works fine thanks!

**Comment by ikheetjeff** [comment]
@fredrikburmester Great stuff! This same issue is on iOS (0.3.4), is this already fixed of should i create a new issue. Thanks for your great work so far.

**Comment by fredrikburmester** [comment]
This should be fixed. Check 0.4.0 please! @ikheetjeff
